import { useEffect, useRef, useState, type FormEvent } from 'react'
import { ArrowUpRight, ArrowRight, Check, ChevronDown, Plus, Minus, Menu, X, ShieldCheck, MoveUpRight, Bike, ShoppingBag, CreditCard, Plane, Layers3, SlidersHorizontal, HeartHandshake, Globe2, CheckCheck, Download } from 'lucide-react'

const industries = [
  { name: 'Mobility', icon: Bike, label: 'FOR THE WAY WE MOVE', title: 'More freedom.\nLess what if.', text: 'From the daily commute to the next adventure. Bring relevant protection into the moment your customers choose their next ride.', tags: ['Bikes & e-bikes', 'Shared mobility', 'Automotive'], image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=1400&q=85', alt: 'A bicycle ready for the next journey', card: 'Every ride. A little more peace of mind.' },
  { name: 'Retail & lifestyle', icon: ShoppingBag, label: 'FOR THE THINGS THEY LOVE', title: 'Great purchases.\nGreater peace of mind.', text: 'Make protection a natural part of checkout. Keep your customers connected to the things they love, with an experience that feels like your brand.', tags: ['Electronics', 'Purchase protection', 'Everyday essentials'], image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1400&q=85', alt: 'A bright, thoughtfully designed retail space', card: 'Their favourite things. Thoughtfully protected.' },
  { name: 'Fintech', icon: CreditCard, label: 'FOR EVERYDAY FINANCIAL LIFE', title: 'More value.\nWith every interaction.', text: 'Bring meaningful protection into your financial ecosystem. Create a connected experience that makes everyday banking feel more useful, and more human.', tags: ['Digital banking', 'Card benefits', 'Member experiences'], image: 'https://images.unsplash.com/photo-1444491741275-3747c53c99b4?auto=format&fit=crop&w=1400&q=85', alt: 'Sunlight falling through a green forest', card: 'A little confidence. Wherever life takes them.' },
  { name: 'Travel', icon: Plane, label: 'FOR THE PLACES THEY GO', title: 'New horizons.\nFewer worries.', text: 'Give your customers one less thing to think about. Build relevant protection into booking, so their next journey starts with confidence.', tags: ['Travel platforms', 'Booking journeys', 'Experiences'], image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85', alt: 'Mountain peaks rising into a clear sky', card: 'Big adventures. A little less uncertainty.' },
]
const faqs = [
  ['What is embedded insurance?', 'Embedded insurance brings protection directly into a product or service your customers already use. Instead of a separate insurance journey, relevant cover becomes part of buying a bike, booking a trip, or using a financial app.'],
  ['Can the experience look and feel like our brand?', 'That is the idea. We design around your customer journey, so the language, interface and experience can feel like a natural extension of your brand. The exact scope is agreed together during discovery.'],
  ['How does a partnership get started?', 'We start with a conversation about your customers, your business and the problem you want to solve. From there, we explore the product, integration and operating model together before agreeing a launch plan.'],
  ['Do we need an in-house insurance team?', 'You do not need to have every answer before starting a conversation. We work together to understand which capabilities you already have, and which insurance, technology and servicing support your programme would need.'],
]
function Logo() { return <a className="logo" href="#home" aria-label="insrt home">insrt<span className="logo-dot">.</span></a> }

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [industry, setIndustry] = useState(0)
  const [faq, setFaq] = useState<number | null>(null)
  const [dialogType, setDialogType] = useState<'contact' | 'privacy'>('contact')
  const [submitted, setSubmitted] = useState(false)
  const [enquiry, setEnquiry] = useState('')
  const dialog = useRef<HTMLDialogElement>(null)
  const current = industries[industry]
  useEffect(() => {
    document.body.style.overflow = menuOpen ? 'hidden' : ''
    return () => { document.body.style.overflow = '' }
  }, [menuOpen])
  function openDialog(type: 'contact' | 'privacy' = 'contact') {
    setMenuOpen(false); setDialogType(type); setSubmitted(false); dialog.current?.showModal()
  }
  function submitEnquiry(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    setEnquiry(`insrt partnership enquiry\n\nName: ${data.get('name')}\nWork email: ${data.get('email')}\nCompany: ${data.get('company')}\nIndustry: ${data.get('industry')}\n\n${data.get('message')}`)
    setSubmitted(true)
  }
  function downloadEnquiry() {
    const url = URL.createObjectURL(new Blob([enquiry], { type: 'text/plain;charset=utf-8' }))
    const link = document.createElement('a'); link.href = url; link.download = 'insrt-partnership-enquiry.txt'; link.click(); URL.revokeObjectURL(url)
  }
  function selectTab(index: number, focus = false) {
    const next = (index + industries.length) % industries.length
    setIndustry(next)
    if (focus) document.getElementById(`industry-tab-${next}`)?.focus()
  }
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="header"><div className="container nav-inner"><Logo /><nav className="desktop-nav" aria-label="Main navigation"><a href="#why-insrt">Why insrt</a><a href="#solutions">Solutions <ChevronDown size={13} /></a><a href="#platform">Our platform</a><a href="#how-it-works">How we work</a></nav><button className="button button-dark nav-cta" onClick={() => openDialog()}>Let’s talk <ArrowUpRight size={17} /></button><button className="menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} aria-controls="mobile-nav" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>
      <nav id="mobile-nav" className={`mobile-nav ${menuOpen ? 'is-open' : ''}`} aria-label="Mobile navigation" hidden={!menuOpen}>{[['Why insrt', '#why-insrt'], ['Solutions', '#solutions'], ['Our platform', '#platform'], ['How we work', '#how-it-works']].map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}<ArrowUpRight /></a>)}<button className="button button-dark" onClick={() => openDialog()}>Let’s talk <ArrowUpRight size={18} /></button></nav>
    </header>
    <main id="main">
      <section id="home" className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="status-dot" /> INSURANCE. IN THE RIGHT PLACE.</div><h1>Life happens.<br />Be right <span className="there-word">there.<svg viewBox="0 0 300 18" preserveAspectRatio="none" aria-hidden="true"><path d="M4 13 Q150 -2 296 8" /></svg></span></h1><p className="hero-description">Insurance that fits into your world.<br className="desktop-break" /> We help you protect your customers, grow your<br className="desktop-break" /> business, and make everyday life a little easier.</p><div className="hero-actions"><button className="button button-dark" onClick={() => openDialog()}>Build with us <ArrowUpRight size={19} /></button><a className="text-link" href="#solutions">Explore the possibilities <ArrowRight size={17} /></a></div><div className="hero-note"><span className="note-icon"><Layers3 size={17} /></span> Your brand. Your customers. Our expertise.</div></div>
        <div className="hero-visual"><img className="hero-image" src="https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1400&q=85" alt="Sunlight streaming through a quiet green forest" fetchPriority="high" /><div className="image-shade" /><div className="visual-label"><span /> MADE FOR REAL LIFE</div><div className="orbit-art" aria-hidden="true"><span /><span /><span /><span /></div><div className="visual-caption">A little protection.<br />A world of possibility.</div><div className="protection-card"><div className="card-icon"><ShieldCheck size={25} strokeWidth={1.5} /></div><div><span className="card-kicker">RIGHT HERE. WITH YOU.</span><strong>You’re good to go.</strong><span className="coverage-status"><span /> Protection, seamlessly embedded</span></div><span className="card-check"><Check size={16} /></span></div><span className="illustration-label">Illustrative customer experience</span></div>
      </section>
      <section className="intro-strip container" aria-label="Our approach"><p>A natural part of your business.<br /><strong>A meaningful part of their life.</strong></p><div className="strip-items"><span><Layers3 /> Embedded by design</span><span><HeartHandshake /> Built around people</span><span><Globe2 /> Made to grow with you</span></div></section>
      <section id="why-insrt" className="section benefits container"><div className="section-top"><div><span className="eyebrow">A BETTER WAY TO INSURE</span><h2>Not an add-on.<br />A perfect fit.</h2></div><p>Good insurance doesn’t get in the way.<br />It shows up when it matters, feels like your brand,<br className="desktop-break" /> and gives your customers a reason to stay.</p></div><div className="benefit-grid"><article className="benefit-card"><span className="line-icon"><HeartHandshake size={28} strokeWidth={1.4} /></span><span className="benefit-number">01</span><h3>Closer to your customers.</h3><p>Turn everyday interactions into lasting relationships. Offer protection that makes sense for the way your customers live.</p></article><article className="benefit-card"><span className="line-icon"><SlidersHorizontal size={28} strokeWidth={1.4} /></span><span className="benefit-number">02</span><h3>Your brand. Front and centre.</h3><p>Your experience, your voice, your customer relationship. We work behind the scenes to make it all feel effortless.</p></article><article className="benefit-card"><span className="line-icon"><MoveUpRight size={28} strokeWidth={1.4} /></span><span className="benefit-number">03</span><h3>New possibilities for growth.</h3><p>Create more value with every interaction. Build an insurance offering that evolves alongside your business.</p></article></div></section>
      <section id="solutions" className="section solutions container"><div className="section-top"><div><span className="eyebrow">YOUR WORLD. OUR STARTING POINT.</span><h2>Protection that<br />belongs.</h2></div><p>Different businesses. Different lives.<br />One simple idea: the right protection,<br />right where your customers need it.</p></div><div className="industry-tabs" role="tablist" aria-label="Explore industries">{industries.map((item, index) => <button key={item.name} id={`industry-tab-${index}`} role="tab" aria-selected={industry === index} aria-controls="industry-panel" tabIndex={industry === index ? 0 : -1} className={industry === index ? 'active' : ''} onClick={() => selectTab(index)} onKeyDown={event => { if (['ArrowRight', 'ArrowLeft', 'Home', 'End'].includes(event.key)) { event.preventDefault(); selectTab(event.key === 'Home' ? 0 : event.key === 'End' ? industries.length - 1 : industry + (event.key === 'ArrowRight' ? 1 : -1), true) } }}><item.icon size={18} />{item.name}<ArrowUpRight className="tab-arrow" size={16} /></button>)}</div><div className="industry-panel" id="industry-panel" role="tabpanel" aria-labelledby={`industry-tab-${industry}`}><div className="industry-copy" key={`${industry}-copy`}><span className="eyebrow">{current.label}</span><h3>{current.title}</h3><p>{current.text}</p><div className="tag-list">{current.tags.map(tag => <span key={tag}>{tag}</span>)}</div><button className="text-link" onClick={() => openDialog()}>Let’s explore your opportunity <ArrowUpRight size={18} /></button></div><div className="industry-photo"><img key={current.image} src={current.image} alt={current.alt} loading="lazy" /><div className="industry-photo-note"><ShieldCheck size={20} /><span>{current.card}</span></div></div></div></section>
      <section id="platform" className="platform-section"><div className="container platform-grid"><div className="platform-copy"><span className="eyebrow">COMPLEX BEHIND THE SCENES. SIMPLE UP FRONT.</span><h2>All the moving parts.<br /><span>One seamless<br />experience.</span></h2><p>Insurance expertise meets connected technology. From the first quote to the moments that matter, we bring the pieces together so you don’t have to.</p><a className="button button-lime" href="#how-it-works">Meet your next partner <ArrowUpRight size={18} /></a><div className="platform-features"><span><Check size={15} /> Brand-first experiences</span><span><Check size={15} /> Connected journeys</span><span><Check size={15} /> Built for evolution</span></div></div><div className="platform-visual" aria-label="Illustration of the insrt platform connecting your brand with insurance services"><div className="platform-top"><span className="small-brand">your brand<span>®</span></span><span className="connected"><span /> Connected</span></div><div className="connection-line"><span /></div><div className="platform-hub"><span className="hub-logo">insrt<span>.</span></span><span>THE EMBEDDED INSURANCE LAYER</span><Layers3 size={22} /></div><div className="flow-lines"><span /><span /><span /></div><div className="service-nodes"><div><SlidersHorizontal size={22} /><span>Quote & cover</span></div><div><ShieldCheck size={22} /><span>Policy & care</span></div><div><HeartHandshake size={22} /><span>Claims & support</span></div></div><div className="code-preview"><span className="code-comment">// Less friction. More possibility.</span><code><span>insrt</span>.protect({'{'}<br />&nbsp; brand: <em>'yours'</em>,<br />&nbsp; experience: <em>'seamless'</em><br />{'}'});</code><span className="code-caption">Illustrative integration</span><CheckCheck className="code-check" size={21} /></div></div></div></section>
      <section id="how-it-works" className="section process container"><div className="section-top"><div><span className="eyebrow">GOOD THINGS START WITH A CONVERSATION</span><h2>From “what if”<br />to what’s next.</h2></div><a className="text-link" href="#contact">Let’s make it happen <ArrowUpRight size={18} /></a></div><div className="process-grid">{[['Discover', 'We get to know your business, your customers, and the opportunity in front of you.'], ['Design', 'Together, we shape the right protection and an experience that feels entirely yours.'], ['Integrate', 'We connect the pieces, align the teams, and get your offering ready for the real world.'], ['Evolve', 'Launch is just the beginning. We learn, refine, and explore what comes next, together.']].map(([title, text], index) => <article key={title}><div className="step-line"><span>0{index + 1}</span>{index < 3 ? <ArrowRight size={20} /> : <Check size={20} />}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="faq-section container"><div><span className="eyebrow">A LITTLE MORE CLARITY</span><h2>Good questions.<br />Straight answers.</h2><p>Something else on your mind?</p><button className="text-link" onClick={() => openDialog()}>Just ask us <ArrowUpRight size={17} /></button></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${faq === index ? 'is-open' : ''}`} key={question}><h3><button aria-expanded={faq === index} aria-controls={`faq-answer-${index}`} id={`faq-question-${index}`} onClick={() => setFaq(faq === index ? null : index)}>{question}{faq === index ? <Minus size={19} /> : <Plus size={19} />}</button></h3><div id={`faq-answer-${index}`} role="region" aria-labelledby={`faq-question-${index}`} hidden={faq !== index}><p>{answer}</p></div></div>)}</div></section>
      <section id="contact" className="contact-section container"><div className="contact-box"><div><span className="eyebrow"><span className="status-dot" /> LET’S BUILD SOMETHING THAT MATTERS</span><h2>Your next chapter.<br />Let’s <span>insrt</span> it.</h2><p>Bring your ideas. We’ll bring the insurance expertise.</p><button className="button button-dark" onClick={() => openDialog()}>Start a conversation <ArrowUpRight size={19} /></button></div><div className="contact-art" aria-hidden="true"><span /><span /><span /><ArrowUpRight /></div></div></section>
    </main>
    <footer className="footer container"><div className="footer-main"><div><Logo /><p>Insurance, right where life happens.</p></div><div className="footer-links"><a href="#why-insrt">Why insrt</a><a href="#solutions">Solutions</a><a href="#platform">Our platform</a><a href="#how-it-works">How we work</a><button onClick={() => openDialog()}>Get in touch <ArrowUpRight size={14} /></button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} insrt. Designed for what’s next.</span><span className="footer-legal"><span>Website concept</span><button onClick={() => openDialog('privacy')}>Privacy & website information <ArrowUpRight size={12} /></button></span></div></footer>
    <dialog ref={dialog} className="enquiry-dialog" aria-labelledby="dialog-title" onClick={event => { if (event.target === event.currentTarget) dialog.current?.close() }}><button className="dialog-close" aria-label="Close dialog" onClick={() => dialog.current?.close()}><X size={22} /></button>
      {dialogType === 'privacy' ? <div className="policy-content"><span className="eyebrow">WEBSITE INFORMATION</span><h2 id="dialog-title">A note on this concept.</h2><p>This is a design prototype for insrt, not a live insurance offer. Industry examples, the protection card and the integration diagram are illustrative.</p><p>No analytics or advertising cookies are used. Images and fonts are loaded from Unsplash and Google Fonts; those services receive the network information necessary to deliver their assets.</p><p>Enquiry details stay in your browser and are not sent to a server or saved by this website. You can download your draft locally.</p><p>Before launch, insrt’s verified legal entity, regulatory information, contact destination and full privacy notice must be added.</p></div> : submitted ? <div className="success-content"><span className="success-icon"><Check size={32} /></span><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2 id="dialog-title">Your draft is ready.</h2><p>This is a website preview, so your enquiry has <strong>not been sent</strong>. Download a copy to keep your ideas handy.</p><button className="button button-dark" onClick={downloadEnquiry}>Download your enquiry <Download size={18} /></button><button className="text-link" onClick={() => dialog.current?.close()}>Back to exploring <ArrowRight size={17} /></button></div> : <><span className="eyebrow">LET’S FIND YOUR PERFECT FIT</span><h2 id="dialog-title">Hello, possibility.</h2><p>Tell us a little about your business and what you have in mind.</p><form onSubmit={submitEnquiry}><div className="form-row"><label>Your name<input name="name" autoComplete="name" placeholder="Alex Andersson" required maxLength={100} /></label><label>Work email<input name="email" type="email" autoComplete="email" placeholder="alex@company.com" required maxLength={200} /></label></div><div className="form-row"><label>Company<input name="company" autoComplete="organization" placeholder="Your company" required maxLength={150} /></label><label>Your industry<select name="industry" defaultValue=""><option value="" disabled>Select an industry</option>{industries.map(item => <option key={item.name}>{item.name}</option>)}<option>Something else</option></select></label></div><label>What are you thinking?<textarea name="message" rows={3} placeholder="Your customers, your ideas, your next big thing…" required maxLength={3000} /></label><p className="form-note">Preview only. Your details stay in your browser. Nothing is sent; you can download your enquiry in the next step.</p><button type="submit" className="button button-dark">Create enquiry draft <ArrowUpRight size={18} /></button></form></>}
    </dialog>
  </>
}